spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/compute
              - https://www.googleapis.com/auth/compute.readonly
              - https://www.googleapis.com/auth/logging.read
        redirect-uri: "{baseUrl}/login/oauth2/code/google"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs



  jpa:
    hibernate:
      ddl-auto: update # 또는 validate, none 등

security:
  crypto:
    aes-key: "4328175493264413"
    aes-iv: "abcdefghijklmnop"

bot:
  token: ${DISCORD_BOT_TOKEN}
