spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gcpassistant
    username: root
    password: keypass
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update # 또는 validate, none 등


bot:
  token: ${DISCORD_BOT_TOKEN}