name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync labels using PAT
        uses: mheap/github-labeler@v1
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
          config: .github/labels.yml